### PR TITLE
Functions and tests skeleton

### PR DESCRIPTION
**Pull request by lenafm**
First functions and tests to discuss package structure and functionality.

@jpmarindiaz have a look at the three R scripts with the function skeletons and at the `test-validate.R`.

### CODE REVIEW

**Comment by lenafm** [comment]
@jpmarindiaz I just updated the examples for the `requirements_load` function. 

If you checkout this branch locally you can see the examples in the reference page for the `requirements_load` function by opening the `pkgdown` site in `docs/index.html`.

**Comment by lenafm** [comment]
@jpmarindiaz do you have any thoughts on these functions/tests?

**Comment by jpmarindiaz** [comment]
Some comments:

- I don't think `dsvalidate` should also do the visualization recommendation. I feel it is out of scope for this package. I had a first version of the viz recommender here https://github.com/jpmarindiaz/pseudoviz/blob/master/R/pseudoviz.R Needs to be updated as I haven't touched it in a couple of years but my point is that each visualization type will have associate a yaml "schema" or "skeleton" for the data.frames, and that should be enough for the recommendation. As long as validations work properly for any specification (yaml files with dataframe requirements) 
- `create_dic_advanced` should go directly in homodatum. Homodatum does already calculate those metrics when fringes are created, we only need to save those stats (schemas) as yaml files in the dictionaries see fringe_io functions and `fringe_write`  `fringe_write_json` that are also used in dspins. We would only need to include the proper meta data to account for those "advanced dictionary" fields
- I think `dsvalidate` should only focus on the `validate_requirements` function and the fringe "skeleton" specification in the yaml

Some comments about the yaml specification:

- We need to add tests so we check the requirement specification (or may we call it the fringe_skeleton) is valid
- There are three levels of specifications, one for groups of tables (how many tables there are and if there are shared keys - we can leave this on hold until we work on the next ones), properties of each table, like the n_cols, n_rows, distinct_rows, etc. And finally other are specs to each field (n_uniques, mean for Num, etc).
- I have added a yaml to the branch file with some ideas for specs

A long time ago I started implementing those validations here https://github.com/datasketch/homodatum/blob/master/R/validate.R but those validations should go in this package.

Here is an examples `skeleton`/`specitication` file for a network and how I think it should be structured.
There should be also some type of sufficiency/need of requirements. Some requirements may be strictly necessary while others suggested, I think all can be required by default but we add a suggested: true in the yaml and return TRUE with warnigns instead of FALSE for that specific check

```
description: This is a network (with nodes and edges)
table: 
  id: nodes # the table name to reference which csv inside a folder to read
    - n_cols:
        greater_than: 2
        #equals: 3
        #less_than: 10
    - n_rows: 
        less_than: 0
    #- n_distinct: # number of distinct rows in dataframe
    - frType: "Uid-Cat-Txt"
        # equals: "Uid-Cat-Txt"
          # - Uid # node id
          # - Cat # label
          # - Txt # description
        # contains:  # We can also check if Cat-Num is a subset 
                     # of all possible combinations of hdTypes (already done in homodatum)
        #   - Cat
        #   - Num
        # # This one can be useful for a looser check when an hdType can be castable
        # to another, say a Num can be converted to a Cat (like a survey response)
        # may_contain:
        #   - Cat
        #   - Num        
  fields:
    - id: id
      - hdType: 
          any_of: [Cat, Num]
        unique: true
        n_unique: 
          greater_than: 10
      - label: at_least_one_categorical_column
        n_cols: 
          greater_than: 0
        condition:
          hdType:
            equals: Cat
  table_id: edges
    - n_cols: 
        equals: 2
    - frType: "Cat-Cat"
    fields:
      - id: source
        hdType: Cat
      - id: target
        hdType: Cat
  # conditions: # additional conditions
  #  - all_nodes_ids_in_edges_must_be_in_source_or_target_fields


```

**Comment by lenafm** [comment]
Thanks for the comments, @jpmarindiaz! 

And thanks for linking to the validate functions you had written a while ago - once I start to actually implement the functions in `dsvalidate` I will use (and potentially update if necessary) those functions that you already created. 

On the more general comments:
- Happy for the recommendations being a different package. I don't feel super strongly about this as I do see some overlap but I also see reasons for it being separate.
- Completely agree that `create_dic_advanced` should be part of `homodatum`. I think I mentioned in the documentation that it could be an optional additional parameter to `create_dic(.., extended = TRUE)` in which the required extra meta data is calculated - would you be happy with that?

On the more yaml specific comments you made:
- 100% agreed that we need to have tests for the requirement specification. I will create `test-load.R` and add some once we have more clarity on the requirements (see my question below).
- On the three levels of specification, I understand number two and number three and I agree, it's a good idea to have a separate section for general properties of the dataset. On the 'groups of tables' specification level - are you referring to the case when multiple datasets are checked?

I have a few questions on the example requirements yaml you included: 
- I think I understand the first section called `table` - it's the general properties for the table that has the label `nodes`, right?
- I'm not sure I understand the `fields` section. I suppose it might have multiple entries for each table (if there are multiple tables)? In this case it says `id: id` but should it be `id: nodes` to refer to the table that is described in the first section? And the fields requirements under `id: id`, is that two different requirements, one being an `id` column and another being a column with a categorical variable?
- I also don't understand how the `table_id` section is different from the `fields` section.

**Comment by jpmarindiaz** [comment]
Yes, let's go with `homodatum::create_dic(.., extended = TRUE)` 

In the groups of tables I mean when some tables need to go together, like when we have networks, where we need a nodes and an edges table. The third level of specification for Fields is for validations for specific columns, like a column named ID should have unique elements.

See updated yaml file:

```
description: This is a network (with nodes and edges)
table: 
  table_id: nodes # the table name to reference which csv inside a folder to read
    specs:
      - n_cols:
          greater_than: 2
          #equals: 3
          #less_than: 10
      - n_rows: 
          less_than: 0
      #- n_distinct: # number of distinct rows in dataframe
      - frType: "Uid-Cat-Txt"
          # equals: "Uid-Cat-Txt"
            # - Uid # node id
            # - Cat # label
            # - Txt # description
          # contains:  # We can also check if Cat-Num is a subset 
                       # of all possible combinations of hdTypes (already done in homodatum)
          #   - Cat
          #   - Num
          # # This one can be useful for a looser check when an hdType can be castable
          # to another, say a Num can be converted to a Cat (like a survey response)
          # may_contain:
          #   - Cat
          #   - Num        
    fields:
      - field_id: id
        specs:
          - hdType: 
              any_of: [Cat, Num]
            unique: true
            n_unique: 
              greater_than: 10
          - label: 
              equals: "ID of a Node"
          # - label: "ID of a Node" ## this could short hand notation for ~equals~
          - n_cols: 
              greater_than: 0
            condition:
              hdType:
                equals: Cat
  table_id: edges
    specs:    
      - n_cols: 
          equals: 2
      - frType: "Cat-Cat"
    fields:
      - field_id: source
        specs: 
          hdType: Cat
      - field_id: target
          hdType: Cat
  # conditions: # additional conditions
  #  - all_nodes_ids_in_edges_must_be_in_source_or_target_fields
```

**Pull request merged**
